# Generated by Django 5.2 on 2025-07-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='list_type',
            field=models.CharField(choices=[('lori', "Lori's List"), ('grocery', 'Grocery List')], default='lori', max_length=10),
        ),
    ]
